# fly.toml app configuration file generated for protohacker-zig on 2024-03-16T21:07:46Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'protohacker-zig'
primary_region = 'lhr'

[env]
  ADDRESS = 'fly-global-services'
  PORT = '5000'

[[services]]
  protocol = 'udp'
  internal_port = 5000

[[services.ports]]
    port = 5000

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
